import ContactUs from '@/components/ContactUs';
import React from 'react';

export const metadata = {
  title: "Tradeswift - Contact Us",
  description: "Generated by Tradeswift - Contact Us",
};
const ContactPage = () => {
  return (
    <div className='max-w-screen-xl mx-auto px-2'>
      <h1 className='text-4xl font-extrabold text-center my-24'>Contact Us</h1>
      <ContactUs></ContactUs>
    </div>
  );
};

export default ContactPage;