import { Mooli } from 'next/font/google'
import './globals.css'

const mooli = Mooli({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: 'Tradeswift',
  description: 'Generated by Tradeswift',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme={'light'}>
      <body className={mooli.className}>{children}</body>
    </html>
  )
}
