
export const metadata = {
  title: `Tradeswift - Blogs page ${id}`,
  description: `Generated by Tradeswift - Blogs page ${id}`,
};
const BlogDetailsPage = () => {
    
 
  const { id } = router.query;
  
  return (
    <div className="blog-details">
      <h2>here is ids content comming soon</h2>
      {/* <h1>{blog.title}</h1>
      <p>{blog.description}</p>
      Add more details as needed */}
    </div>
  );
};

export default BlogDetailsPage;
